### ISSUE TITLE
Debug Assertion Failed when importing an fbx with .meta

### ISSUE THREAD

**Issue by auusi9** [traguill/Project3#29]
Description: When trying to import a new mesh with .meta engine crashes.

Steps to reproduce: 1- Copy and paste an fbx with his meta from Assets(outside game) to Game/Assets
2- Make sure there is no library folder for this fbx
3- Run the engine
4- Debug assertion failed

**Comment by traguill** [comment]
The meta files from Assets outside the game are outdated. Do not use them
